version: "3.7"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: arapaimas
      POSTGRES_PASSWORD: arapaimas
      POSTGRES_USER: arapaimas
    ports:
      - "127.0.0.1:5000:5432"

  elections:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./log:/app/log
      - .:/app:ro
    tty: true
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      DATABASE_URL: "postgresql://arapaimas:arapaimas@postgres:5432/arapaimas"
